"""
Debug Distillation Output
=========================

Analyze what was actually generated by the distillation process.
Use this to understand why data was removed during cleaning.

Usage:
    python scripts/debug_distillation_output.py --output-dir outputs/merged
    python scripts/debug_distillation_output.py --cleaning-report outputs/cleaned/cleaning_report.json
"""

import argparse
import json
from pathlib import Path
from typing import Dict, Any, List


def analyze_distilled_file(file_path: Path) -> Dict[str, Any]:
    """Analyze a single distilled JSON file."""
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    image_id = data.get('image_id')
    tasks = data.get('tasks', {})

    analysis = {
        'image_id': image_id,
        'file': str(file_path),
        'tasks_found': list(tasks.keys()),
        'task_details': {},
        'has_empty_results': False,
        'empty_tasks': [],
        'warnings': [],
    }

    for task_name, task_data in tasks.items():
        task_analysis = {
            'has_hard_label': 'hard_label' in task_data,
            'has_soft_label': 'soft_label' in task_data,
            'has_cot': 'cot_reasoning' in task_data,
        }

        # Check for empty results
        if task_name == 'vqa':
            hard_label = task_data.get('hard_label', {})
            answer = hard_label.get('answer', '')
            confidence = hard_label.get('confidence', 0.0)

            task_analysis['answer'] = answer
            task_analysis['confidence'] = confidence
            task_analysis['answer_length'] = len(answer)

            if not answer or answer.lower() in ['unknown', 'n/a', 'none', '']:
                analysis['has_empty_results'] = True
                analysis['empty_tasks'].append(task_name)
                analysis['warnings'].append(f"VQA: Empty or invalid answer '{answer}'")

            if confidence < 0.5:
                analysis['warnings'].append(f"VQA: Low confidence {confidence:.2f}")

        elif task_name == 'captioning':
            hard_label = task_data.get('hard_label', {})
            captions = hard_label.get('captions', [])

            task_analysis['num_captions'] = len(captions)
            task_analysis['captions'] = captions[:2] if captions else []  # Show first 2

            if not captions or len(captions) == 0:
                analysis['has_empty_results'] = True
                analysis['empty_tasks'].append(task_name)
                analysis['warnings'].append("Captioning: No captions generated")

            # Check caption lengths
            short_captions = [cap for cap in captions if len(cap.strip()) < 10]
            if short_captions:
                analysis['warnings'].append(f"Captioning: {len(short_captions)} short captions (<10 chars)")

        elif task_name == 'detection':
            hard_label = task_data.get('hard_label', {})
            objects = hard_label.get('objects', [])

            task_analysis['num_objects'] = len(objects)
            task_analysis['object_classes'] = [
                obj.get('class', obj.get('category_name', 'unknown'))
                for obj in objects[:3]  # Show first 3
            ]

            if not objects or len(objects) == 0:
                analysis['has_empty_results'] = True
                analysis['empty_tasks'].append(task_name)
                analysis['warnings'].append("Detection: No objects detected")

            # Check confidence of objects
            low_conf_objects = [obj for obj in objects if obj.get('confidence', 1.0) < 0.5]
            if low_conf_objects:
                analysis['warnings'].append(f"Detection: {len(low_conf_objects)} low confidence objects")

        # Check CoT quality
        cot = task_data.get('cot_reasoning', {})
        if cot:
            reasoning = cot.get('raw_reasoning', '')
            quality_metrics = cot.get('quality_metrics', {})

            task_analysis['cot_length'] = len(reasoning)
            task_analysis['cot_steps'] = quality_metrics.get('step_count', 0)
            task_analysis['cot_logical_flow'] = quality_metrics.get('logical_flow_score', 0.0)

            if quality_metrics.get('logical_flow_score', 0) < 0.5:
                analysis['warnings'].append(f"{task_name}: Low CoT quality score")
        else:
            analysis['warnings'].append(f"{task_name}: No CoT reasoning generated")

        analysis['task_details'][task_name] = task_analysis

    return analysis


def analyze_cleaning_report(report_path: Path) -> Dict[str, Any]:
    """Analyze cleaning report to understand removal reasons."""
    with open(report_path, 'r', encoding='utf-8') as f:
        report = json.load(f)

    summary = {
        'total_input': report['summary']['total_input'],
        'cleaned_count': report['summary']['cleaned_count'],
        'removed_count': report['summary']['removed_count'],
        'removal_rate': report['summary']['removal_rate'],
        'avg_quality': report['quality_statistics']['average_quality_score'],
        'anomaly_counts': report['anomaly_statistics'],
    }

    # Analyze removed samples
    removed_samples = report.get('removed_samples', [])
    removal_reasons_count = {}

    for sample in removed_samples:
        for reason in sample.get('reasons', []):
            # Extract reason type
            reason_type = reason.split('=')[0] if '=' in reason else reason
            removal_reasons_count[reason_type] = removal_reasons_count.get(reason_type, 0) + 1

    summary['removal_reasons_breakdown'] = removal_reasons_count

    return summary


def print_analysis(analysis: Dict[str, Any]) -> None:
    """Print analysis results."""
    print("\n" + "="*70)
    print(f"IMAGE ID: {analysis['image_id']}")
    print("="*70)

    print(f"\nTasks found: {analysis['tasks_found']}")
    print(f"Has empty results: {analysis['has_empty_results']}")
    if analysis['empty_tasks']:
        print(f"Empty tasks: {analysis['empty_tasks']}")

    # Print task details
    for task_name, details in analysis['task_details'].items():
        print(f"\n[{task_name.upper()}]")
        print(f"  Hard label: {details.get('has_hard_label')}")
        print(f"  Soft label: {details.get('has_soft_label')}")
        print(f"  CoT: {details.get('has_cot')}")

        if task_name == 'vqa':
            print(f"  Answer: '{details.get('answer', 'N/A')}'")
            print(f"  Confidence: {details.get('confidence', 0):.2f}")
            print(f"  Answer length: {details.get('answer_length', 0)}")

        elif task_name == 'captioning':
            print(f"  Num captions: {details.get('num_captions', 0)}")
            if details.get('captions'):
                print(f"  Sample captions:")
                for i, cap in enumerate(details['captions'][:2], 1):
                    print(f"    {i}. {cap[:60]}...")

        elif task_name == 'detection':
            print(f"  Num objects: {details.get('num_objects', 0)}")
            if details.get('object_classes'):
                print(f"  Detected classes: {details['object_classes']}")

        # CoT info
        if details.get('has_cot'):
            print(f"  CoT length: {details.get('cot_length', 0)} chars")
            print(f"  CoT steps: {details.get('cot_steps', 0)}")
            print(f"  CoT logical flow: {details.get('cot_logical_flow', 0):.2f}")

    # Print warnings
    if analysis['warnings']:
        print(f"\n⚠ WARNINGS:")
        for warning in analysis['warnings']:
            print(f"  - {warning}")


def main():
    parser = argparse.ArgumentParser(
        description="Debug distillation output to understand cleaning behavior"
    )

    parser.add_argument(
        '--output-dir',
        type=str,
        default='outputs/merged',
        help='Directory containing distilled JSON files'
    )

    parser.add_argument(
        '--cleaning-report',
        type=str,
        default='outputs/cleaned/cleaning_report.json',
        help='Path to cleaning report JSON'
    )

    parser.add_argument(
        '--limit',
        type=int,
        default=5,
        help='Maximum number of files to analyze'
    )

    args = parser.parse_args()

    # Analyze distilled files
    output_dir = Path(args.output_dir)
    if output_dir.exists():
        json_files = list(output_dir.glob("*.json"))
        # Filter out checkpoint and summary files
        json_files = [
            f for f in json_files
            if not f.name.startswith('checkpoint')
            and not f.name.startswith('merged_summary')
            and not f.name.startswith('cleaning_report')
        ]

        print(f"\nFound {len(json_files)} distilled files in {output_dir}")

        if json_files:
            print(f"\nAnalyzing first {min(args.limit, len(json_files))} files...")

            for json_file in json_files[:args.limit]:
                analysis = analyze_distilled_file(json_file)
                print_analysis(analysis)
    else:
        print(f"\n⚠ Output directory not found: {output_dir}")

    # Analyze cleaning report
    report_path = Path(args.cleaning_report)
    if report_path.exists():
        print("\n" + "="*70)
        print("CLEANING REPORT ANALYSIS")
        print("="*70)

        summary = analyze_cleaning_report(report_path)

        print(f"\nSummary:")
        print(f"  Total input: {summary['total_input']}")
        print(f"  Cleaned: {summary['cleaned_count']}")
        print(f"  Removed: {summary['removed_count']}")
        print(f"  Removal rate: {summary['removal_rate']*100:.1f}%")
        print(f"  Average quality: {summary['avg_quality']:.2f}/100")

        print(f"\nAnomaly counts:")
        for anomaly_type, count in summary['anomaly_counts'].items():
            print(f"  {anomaly_type}: {count}")

        print(f"\nRemoval reasons breakdown:")
        for reason, count in summary['removal_reasons_breakdown'].items():
            print(f"  {reason}: {count}")
    else:
        print(f"\n⚠ Cleaning report not found: {report_path}")


if __name__ == "__main__":
    main()